### ISSUE TITLE
Cinebar Lux - nodes not working?!

### ISSUE THREAD

**Issue by heliMan0815** [Alex9779/node-red-contrib-raumfeld#6]
The raumfeld nodes were working well so far or at least I was able to put workarounds in place to get my things done. So far so good and thanks for your work!

Now, today I´ve got my soundbar Cinebar Lux, added it to the system and control via the app works well :-)
But, I´ve realized, that the raumfeld nodes seems to be not able to deal with the Lux. No command is working, nor status´s cannot be retrieved.

What I´ve tried so far:

Restart of node red server >> did not solve the issue
Deactivated/activated the flows >> did not solve the issue
Deleted the raumfeld config node and added it again >> did not solve the issue

Any idea what I could try further?

BR
Thomas

**Comment by Alex9779** [comment]
Unfortunately I have no Cinebar Lux to test, and I am having troubles to set up a proper dev environment at the moment too to track some smaller issues I have.
To be honest I don't think I can do much about it because I just use the raumkernel lib and consume it in the nodes. (https://github.com/ChriD/node-raumkernel)
I assume the problem is there as in the nodes just the abstract methods for controlling speakers and other stuff is used. Maybe the Cinebar Lux uses some different comm method or certain aspects are different and the kernel does not handle them correct.

I have no idea how much into developing with NodeJS you are, personally I would just take the kernel and test with that, the kernel repo contains a demo file, you could write a simple script using the lib and pushing some command and monitor the logs.

**Comment by Alex9779** [comment]
Think we can close here now...

**Comment by heliMan0815** [comment]
Hey, sorry, I've lost this from my radar.

BR
Thomas Schäfer

Alexander Leisentritt ***@***.***> schrieb am Do., 11. Nov.
2021, 18:29:

**Comment by Alex9779** [comment]
Yeah sorry but I don't think I can assist here, as you might have seen I published a new version with some fixes as I was finally able to get a dev env working again but as I don't own a Cinebar Lux I can't debug with it...
