### ISSUE TITLE
Problems loading anything else than radio stations

### ISSUE THREAD

**Issue by Jogi284** [Alex9779/node-red-contrib-raumfeld#7]
Hi Alex9779,

Thanks for this node red integration of teufel speakers.

Using it to load a favorite radio station with the load favorite node was pretty straight forward. However I would like to also run specific artists or playlists and I saw that you implemented also the artist and album section into the favorite node but somehow I cant manage to load anything out of the albums or artists containers.
Unfortunately, using the load playlist node always gives me "ReferenceError: MYPLAYLISTS is not defined."
Can you help me out here? Where can I define the myplaylists list or how do I have to type in the name of the artist or album in the load favorite node?

Thanks in advance

**Comment by Alex9779** [comment]
Heya, my apologies, I implemented all the stuff a long time ago and relied on the Raumkernel.
It seems that changes since then made some parts not working anymore and unfortunately I am not able to get a development environment running again where I can debug and monitor what the kernel does.

I tested what you said and the error is a result from a call in that line I assume: https://github.com/Alex9779/node-red-contrib-raumfeld/blob/43da6414b3830205e2249186afd2c9160a15143d/nodes/raumfeld-room-load-playlist.js#L36
Obviously the structure of what has to be parsed has changed.

I tried some weeks ago again to get a dev env but I didn't manage to get it going. The example scripts of the kernel do not work anymore for me and I am not so into NodeJS and developing with and for it.

So for the moment, really sorry, I can't fix that...

**Comment by Alex9779** [comment]
Ok I dug into it again and it seems I can get back into development, I get debug messages again...
So give me a little time maybe over the weekend, monday is a holiday here so maybe I find some time...

**Comment by Alex9779** [comment]
Ah well... When something works you can't get away from fixing stuff :P
So I just published 1.0.23 on npmjs with some fixes, loading favorites works now for me with all possible items (radio, playlist, album, artist, title, misc).
And loading playlists should work too.
I also fixed 'is-playing' when you use Spotify, that bothered me a long time...

**Comment by Jogi284** [comment]
Hey Alex,
Thank you so much for fixing that. Works great for me now. Made my day. 
One question though: would it be also possible to pass a payload coming from the trigger node into for example the room or favorite or playlist variable?

My idea is to build a kind of juke box with my teufel system using NFC cards as source directing the teufel system to a certain playlist or album.

Thank you very much again and if you have a tipp how I can realize my idea either with the raumfeld nodes or otherwise I would be very happy.

Enjoy the long weekend!

**Comment by Alex9779** [comment]
> Hey Alex, Thank you so much for fixing that. Works great for me now. Made my day.

Good to hear it works not only for me...

> One question though: would it be also possible to pass a payload coming from the trigger node into for example the room or favorite or playlist variable?
> 
> My idea is to build a kind of juke box with my teufel system using NFC cards as source directing the teufel system to a certain playlist or album.
> 
> Thank you very much again and if you have a tipp how I can realize my idea either with the raumfeld nodes or otherwise I would be very happy.

The nodes accept input on certain msg properties, it's all in the docs of each node. For example the "raumfeld room load playlist" accepts msg.payload or msg.playlist with the name of the playlist to load, msg.roomNames with an array of room names and also for volumes... Every option you can set with the GUI in the node you can also pass into it...

**Comment by Alex9779** [comment]
Think we can close here now...
